vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        media_object:
            uri_prefix: "%env(AWS_S3_BASE_URL)%/%env(AWS_S3_BUCKET_NAME)%/medias"
            upload_destination: 'medias.storage'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
            
