framework:
    workflows:
        gift_publishing:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Gift
            initial_marking: draft
            places:
                - draft
                - ordered
                - published
            transitions:
                checkout:
                    from: draft
                    to: ordered
                publish:
                    from: ordered
                    to: published

